version: '3.7'

services:

  db:
    image: mongo:latest
    volumes:
      - db:/data/db

  giuseppe:
    build:
      context: .
    init: true
    volumes:
      - ./config.json:/home/appuser/config.json:ro
    depends_on:
      - db

volumes:
  db:
    driver: local
